services:
  web-app:    
    container_name: lrts-web
    build: .
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      - PASSWORD=lrts1230
      - HOST=db
      - ConnectionStrings__DefaultConnection=host=db;Database=lrts-db;port=5432;username=admin;Password=lrts1230

  db:
    image: abdulhady/lrts
    container_name: lrts-database
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "lrts1230"
      POSTGRES_USER: "admin"
      POSTGRES_DB: "lrts-db"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/db_init.sql
    restart: unless-stopped
