--
-- PostgreSQL database dump
--

-- Dumped from database version 16.1 (Debian 16.1-1.pgdg120+1)
-- Dumped by pg_dump version 16.1 (Debian 16.1-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE ONLY public."Users" DROP CONSTRAINT "lnk_User_University";
ALTER TABLE ONLY public."Libraries" DROP CONSTRAINT "lnk_University_Library";
ALTER TABLE ONLY public."Users" DROP CONSTRAINT "lnk_Reservation_User";
ALTER TABLE ONLY public."Blocks" DROP CONSTRAINT "lnk_Library_Block";
ALTER TABLE ONLY public."Floors" DROP CONSTRAINT "lnk_Block_Floor";
ALTER TABLE ONLY public."Desks" DROP CONSTRAINT "FK_Desks_Universities_UniversityId";
ALTER TABLE ONLY public."Desks" DROP CONSTRAINT "FK_Desks_Reservations_ReservationId";
ALTER TABLE ONLY public."Desks" DROP CONSTRAINT "FK_Desks_Floors_FloorId";
ALTER TABLE ONLY public."Desks" DROP CONSTRAINT "FK_Desks_Blocks_BlockId";
DROP INDEX public."IX_Users_UniversityId";
DROP INDEX public."IX_Users_ReservationId";
DROP INDEX public."IX_Libraries_UniversityId";
DROP INDEX public."IX_Floors_BlockId";
DROP INDEX public."IX_Desks_UniversityId";
DROP INDEX public."IX_Desks_ReservationId";
DROP INDEX public."IX_Desks_FloorId";
DROP INDEX public."IX_Desks_BlockId";
DROP INDEX public."IX_Blocks_LibraryId";
ALTER TABLE ONLY public."__EFMigrationsHistory" DROP CONSTRAINT "PK___EFMigrationsHistory";
ALTER TABLE ONLY public."Users" DROP CONSTRAINT "PK_Users";
ALTER TABLE ONLY public."Universities" DROP CONSTRAINT "PK_Universities";
ALTER TABLE ONLY public."Scanners" DROP CONSTRAINT "PK_Scanners";
ALTER TABLE ONLY public."Reservations" DROP CONSTRAINT "PK_Reservations";
ALTER TABLE ONLY public."Libraries" DROP CONSTRAINT "PK_Libraries";
ALTER TABLE ONLY public."Floors" DROP CONSTRAINT "PK_Floors";
ALTER TABLE ONLY public."Desks" DROP CONSTRAINT "PK_Desks";
ALTER TABLE ONLY public."Blocks" DROP CONSTRAINT "PK_Blocks";
DROP TABLE public."__EFMigrationsHistory";
DROP TABLE public."Users";
DROP TABLE public."Universities";
DROP TABLE public."Scanners";
DROP TABLE public."Reservations";
DROP TABLE public."Libraries";
DROP TABLE public."Floors";
DROP TABLE public."Desks";
DROP TABLE public."Blocks";
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Blocks; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."Blocks" (
    "Id" integer NOT NULL,
    "LibraryId" integer NOT NULL
);


ALTER TABLE public."Blocks" OWNER TO admin;

--
-- Name: Blocks_Id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public."Blocks" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Blocks_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Desks; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."Desks" (
    "Id" integer NOT NULL,
    "DeskStatus" text NOT NULL,
    "DeskCapacity" integer NOT NULL,
    "UniversityId" integer NOT NULL,
    "FloorId" integer NOT NULL,
    "BlockId" integer NOT NULL,
    "ReservationId" integer
);


ALTER TABLE public."Desks" OWNER TO admin;

--
-- Name: Desks_Id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public."Desks" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Desks_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Floors; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."Floors" (
    "Id" integer NOT NULL,
    "BlockId" integer NOT NULL
);


ALTER TABLE public."Floors" OWNER TO admin;

--
-- Name: Floors_Id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public."Floors" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Floors_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Libraries; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."Libraries" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "UniversityId" integer NOT NULL
);


ALTER TABLE public."Libraries" OWNER TO admin;

--
-- Name: Libraries_Id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public."Libraries" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Libraries_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Reservations; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."Reservations" (
    "Id" integer NOT NULL,
    "UserId" integer NOT NULL,
    "DeskId" integer NOT NULL,
    "StartDateTime" timestamp without time zone NOT NULL,
    "EndDateTime" timestamp without time zone NOT NULL,
    "StartBreak" timestamp without time zone,
    "EndBreak" timestamp without time zone,
    "RemainingBreakTimeInMinutes" integer NOT NULL,
    "ReservationStatus" text NOT NULL
);


ALTER TABLE public."Reservations" OWNER TO admin;

--
-- Name: Reservations_Id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public."Reservations" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Reservations_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Scanners; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."Scanners" (
    "ScannerId" integer NOT NULL
);


ALTER TABLE public."Scanners" OWNER TO admin;

--
-- Name: Scanners_ScannerId_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public."Scanners" ALTER COLUMN "ScannerId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Scanners_ScannerId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Universities; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."Universities" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL
);


ALTER TABLE public."Universities" OWNER TO admin;

--
-- Name: Universities_Id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public."Universities" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Universities_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Users; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."Users" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "UniversityId" integer NOT NULL,
    "ReservationId" integer,
    "HasAccess" boolean NOT NULL,
    "UserType" text NOT NULL,
    "CurrentUserStatus" text NOT NULL,
    "PreviousUserStatus" text NOT NULL,
    "PenaltyScore" real DEFAULT 0 NOT NULL
);


ALTER TABLE public."Users" OWNER TO admin;

--
-- Name: Users_Id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public."Users" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Users_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO admin;

--
-- Data for Name: Blocks; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public."Blocks" ("Id", "LibraryId") FROM stdin;
1	1
\.


--
-- Data for Name: Desks; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public."Desks" ("Id", "DeskStatus", "DeskCapacity", "UniversityId", "FloorId", "BlockId", "ReservationId") FROM stdin;
1	EMPTY	1	1	1	1	1
\.


--
-- Data for Name: Floors; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public."Floors" ("Id", "BlockId") FROM stdin;
1	1
\.


--
-- Data for Name: Libraries; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public."Libraries" ("Id", "Name", "UniversityId") FROM stdin;
1	Sau Kütüphane	1
\.


--
-- Data for Name: Reservations; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public."Reservations" ("Id", "UserId", "DeskId", "StartDateTime", "EndDateTime", "StartBreak", "EndBreak", "RemainingBreakTimeInMinutes", "ReservationStatus") FROM stdin;
1	1	1	2024-01-01 09:05:06	2024-01-01 12:05:06	2024-01-01 10:05:06	2024-01-01 11:05:06	60	IS_ACTIVE
\.


--
-- Data for Name: Scanners; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public."Scanners" ("ScannerId") FROM stdin;
\.


--
-- Data for Name: Universities; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public."Universities" ("Id", "Name") FROM stdin;
1	Sakarya Üniversitesi
\.


--
-- Data for Name: Users; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public."Users" ("Id", "Name", "UniversityId", "ReservationId", "HasAccess", "UserType", "CurrentUserStatus", "PreviousUserStatus", "PenaltyScore") FROM stdin;
1	Ahmet	1	\N	t	STUDENT	OUTSIDE	OUTSIDE	0
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20231220131052_Init	7.0.13
20231220134010_penaltyScore	7.0.13
20231220140359_nullableBreakTimes	7.0.13
\.


--
-- Name: Blocks_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public."Blocks_Id_seq"', 1, false);


--
-- Name: Desks_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public."Desks_Id_seq"', 1, false);


--
-- Name: Floors_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public."Floors_Id_seq"', 1, false);


--
-- Name: Libraries_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public."Libraries_Id_seq"', 1, false);


--
-- Name: Reservations_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public."Reservations_Id_seq"', 1, false);


--
-- Name: Scanners_ScannerId_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public."Scanners_ScannerId_seq"', 1, false);


--
-- Name: Universities_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public."Universities_Id_seq"', 1, false);


--
-- Name: Users_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public."Users_Id_seq"', 1, false);


--
-- Name: Blocks PK_Blocks; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Blocks"
    ADD CONSTRAINT "PK_Blocks" PRIMARY KEY ("Id");


--
-- Name: Desks PK_Desks; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Desks"
    ADD CONSTRAINT "PK_Desks" PRIMARY KEY ("Id");


--
-- Name: Floors PK_Floors; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Floors"
    ADD CONSTRAINT "PK_Floors" PRIMARY KEY ("Id");


--
-- Name: Libraries PK_Libraries; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Libraries"
    ADD CONSTRAINT "PK_Libraries" PRIMARY KEY ("Id");


--
-- Name: Reservations PK_Reservations; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Reservations"
    ADD CONSTRAINT "PK_Reservations" PRIMARY KEY ("Id");


--
-- Name: Scanners PK_Scanners; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Scanners"
    ADD CONSTRAINT "PK_Scanners" PRIMARY KEY ("ScannerId");


--
-- Name: Universities PK_Universities; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Universities"
    ADD CONSTRAINT "PK_Universities" PRIMARY KEY ("Id");


--
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: IX_Blocks_LibraryId; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_Blocks_LibraryId" ON public."Blocks" USING btree ("LibraryId");


--
-- Name: IX_Desks_BlockId; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_Desks_BlockId" ON public."Desks" USING btree ("BlockId");


--
-- Name: IX_Desks_FloorId; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_Desks_FloorId" ON public."Desks" USING btree ("FloorId");


--
-- Name: IX_Desks_ReservationId; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_Desks_ReservationId" ON public."Desks" USING btree ("ReservationId");


--
-- Name: IX_Desks_UniversityId; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_Desks_UniversityId" ON public."Desks" USING btree ("UniversityId");


--
-- Name: IX_Floors_BlockId; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_Floors_BlockId" ON public."Floors" USING btree ("BlockId");


--
-- Name: IX_Libraries_UniversityId; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_Libraries_UniversityId" ON public."Libraries" USING btree ("UniversityId");


--
-- Name: IX_Users_ReservationId; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_Users_ReservationId" ON public."Users" USING btree ("ReservationId");


--
-- Name: IX_Users_UniversityId; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_Users_UniversityId" ON public."Users" USING btree ("UniversityId");


--
-- Name: Desks FK_Desks_Blocks_BlockId; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Desks"
    ADD CONSTRAINT "FK_Desks_Blocks_BlockId" FOREIGN KEY ("BlockId") REFERENCES public."Blocks"("Id") ON DELETE CASCADE;


--
-- Name: Desks FK_Desks_Floors_FloorId; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Desks"
    ADD CONSTRAINT "FK_Desks_Floors_FloorId" FOREIGN KEY ("FloorId") REFERENCES public."Floors"("Id") ON DELETE CASCADE;


--
-- Name: Desks FK_Desks_Reservations_ReservationId; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Desks"
    ADD CONSTRAINT "FK_Desks_Reservations_ReservationId" FOREIGN KEY ("ReservationId") REFERENCES public."Reservations"("Id");


--
-- Name: Desks FK_Desks_Universities_UniversityId; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Desks"
    ADD CONSTRAINT "FK_Desks_Universities_UniversityId" FOREIGN KEY ("UniversityId") REFERENCES public."Universities"("Id") ON DELETE CASCADE;


--
-- Name: Floors lnk_Block_Floor; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Floors"
    ADD CONSTRAINT "lnk_Block_Floor" FOREIGN KEY ("BlockId") REFERENCES public."Blocks"("Id") ON DELETE CASCADE;


--
-- Name: Blocks lnk_Library_Block; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Blocks"
    ADD CONSTRAINT "lnk_Library_Block" FOREIGN KEY ("LibraryId") REFERENCES public."Libraries"("Id") ON DELETE CASCADE;


--
-- Name: Users lnk_Reservation_User; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "lnk_Reservation_User" FOREIGN KEY ("ReservationId") REFERENCES public."Reservations"("Id");


--
-- Name: Libraries lnk_University_Library; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Libraries"
    ADD CONSTRAINT "lnk_University_Library" FOREIGN KEY ("UniversityId") REFERENCES public."Universities"("Id") ON DELETE CASCADE;


--
-- Name: Users lnk_User_University; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "lnk_User_University" FOREIGN KEY ("UniversityId") REFERENCES public."Universities"("Id") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

