--
-- PostgreSQL database dump
--

-- Dumped from database version 16.1 (Debian 16.1-1.pgdg120+1)
-- Dumped by pg_dump version 16.0

-- Started on 2023-12-24 14:25:03

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- TOC entry 3446 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 215 (class 1259 OID 24576)
-- Name: Blocks; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."Blocks" (
    "Id" integer NOT NULL,
    "LibraryId" integer NOT NULL
);


ALTER TABLE public."Blocks" OWNER TO admin;

--
-- TOC entry 216 (class 1259 OID 24579)
-- Name: Blocks_Id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public."Blocks" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Blocks_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 24580)
-- Name: Desks; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."Desks" (
    "Id" integer NOT NULL,
    "DeskStatus" text NOT NULL,
    "DeskCapacity" integer NOT NULL,
    "UniversityId" integer NOT NULL,
    "FloorId" integer NOT NULL,
    "BlockId" integer NOT NULL,
    "ReservationId" integer
);


ALTER TABLE public."Desks" OWNER TO admin;

--
-- TOC entry 218 (class 1259 OID 24585)
-- Name: Desks_Id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public."Desks" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Desks_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 24586)
-- Name: Floors; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."Floors" (
    "Id" integer NOT NULL,
    "BlockId" integer NOT NULL
);


ALTER TABLE public."Floors" OWNER TO admin;

--
-- TOC entry 220 (class 1259 OID 24589)
-- Name: Floors_Id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public."Floors" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Floors_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 24590)
-- Name: Libraries; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."Libraries" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "UniversityId" integer NOT NULL
);


ALTER TABLE public."Libraries" OWNER TO admin;

--
-- TOC entry 222 (class 1259 OID 24595)
-- Name: Libraries_Id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public."Libraries" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Libraries_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 24596)
-- Name: Reservations; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."Reservations" (
    "Id" integer NOT NULL,
    "UserId" integer NOT NULL,
    "DeskId" integer NOT NULL,
    "StartDateTime" timestamp without time zone NOT NULL,
    "EndDateTime" timestamp without time zone NOT NULL,
    "StartBreak" timestamp without time zone,
    "EndBreak" timestamp without time zone,
    "RemainingBreakTimeInMinutes" integer NOT NULL,
    "ReservationStatus" text NOT NULL
);


ALTER TABLE public."Reservations" OWNER TO admin;

--
-- TOC entry 224 (class 1259 OID 24601)
-- Name: Reservations_Id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public."Reservations" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Reservations_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 24602)
-- Name: Scanners; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."Scanners" (
    "ScannerId" integer NOT NULL
);


ALTER TABLE public."Scanners" OWNER TO admin;

--
-- TOC entry 226 (class 1259 OID 24605)
-- Name: Scanners_ScannerId_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public."Scanners" ALTER COLUMN "ScannerId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Scanners_ScannerId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 24606)
-- Name: Universities; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."Universities" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL
);


ALTER TABLE public."Universities" OWNER TO admin;

--
-- TOC entry 228 (class 1259 OID 24611)
-- Name: Universities_Id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public."Universities" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Universities_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 24612)
-- Name: Users; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."Users" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "UniversityId" integer NOT NULL,
    "ReservationId" integer,
    "HasAccess" boolean NOT NULL,
    "UserType" text NOT NULL,
    "CurrentUserStatus" text NOT NULL,
    "PreviousUserStatus" text NOT NULL,
    "PenaltyScore" real DEFAULT 0 NOT NULL,
    "CardId" text DEFAULT ''::text NOT NULL
);


ALTER TABLE public."Users" OWNER TO admin;

--
-- TOC entry 230 (class 1259 OID 24618)
-- Name: Users_Id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public."Users" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Users_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 24619)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO admin;

--
-- TOC entry 3424 (class 0 OID 24576)
-- Dependencies: 215
-- Data for Name: Blocks; Type: TABLE DATA; Schema: public; Owner: admin
--

INSERT INTO public."Blocks" VALUES (1, 1);


--
-- TOC entry 3426 (class 0 OID 24580)
-- Dependencies: 217
-- Data for Name: Desks; Type: TABLE DATA; Schema: public; Owner: admin
--

INSERT INTO public."Desks" VALUES (1, 'OCCUPIED', 1, 1, 1, 1, 1);


--
-- TOC entry 3428 (class 0 OID 24586)
-- Dependencies: 219
-- Data for Name: Floors; Type: TABLE DATA; Schema: public; Owner: admin
--

INSERT INTO public."Floors" VALUES (1, 1);


--
-- TOC entry 3430 (class 0 OID 24590)
-- Dependencies: 221
-- Data for Name: Libraries; Type: TABLE DATA; Schema: public; Owner: admin
--

INSERT INTO public."Libraries" VALUES (1, 'Sau Kütüphane', 1);


--
-- TOC entry 3432 (class 0 OID 24596)
-- Dependencies: 223
-- Data for Name: Reservations; Type: TABLE DATA; Schema: public; Owner: admin
--

INSERT INTO public."Reservations" VALUES (1, 1, 1, '2023-12-24 14:05:06', '2023-12-24 14:15:06', NULL, NULL, 54, 'IN_PROGRESS');


--
-- TOC entry 3434 (class 0 OID 24602)
-- Dependencies: 225
-- Data for Name: Scanners; Type: TABLE DATA; Schema: public; Owner: admin
--



--
-- TOC entry 3436 (class 0 OID 24606)
-- Dependencies: 227
-- Data for Name: Universities; Type: TABLE DATA; Schema: public; Owner: admin
--

INSERT INTO public."Universities" VALUES (1, 'Sakarya Üniversitesi');


--
-- TOC entry 3438 (class 0 OID 24612)
-- Dependencies: 229
-- Data for Name: Users; Type: TABLE DATA; Schema: public; Owner: admin
--

INSERT INTO public."Users" VALUES (2, 'Ahmet', 1, NULL, true, 'STUDENT', 'IN_BREAK', 'IN_LIBRARY', 0, '607952102');
INSERT INTO public."Users" VALUES (1, 'Hadi', 1, 1, true, 'STUDENT', 'OUTSIDE', 'OUTSIDE', 0, '2371228715');


--
-- TOC entry 3440 (class 0 OID 24619)
-- Dependencies: 231
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: admin
--

INSERT INTO public."__EFMigrationsHistory" VALUES ('20231220131052_Init', '7.0.13');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20231220134010_penaltyScore', '7.0.13');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20231220140359_nullableBreakTimes', '7.0.13');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20231224102114_cardId', '7.0.13');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20231224110919_IX_cardID_required', '7.0.13');


--
-- TOC entry 3447 (class 0 OID 0)
-- Dependencies: 216
-- Name: Blocks_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public."Blocks_Id_seq"', 1, false);


--
-- TOC entry 3448 (class 0 OID 0)
-- Dependencies: 218
-- Name: Desks_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public."Desks_Id_seq"', 1, false);


--
-- TOC entry 3449 (class 0 OID 0)
-- Dependencies: 220
-- Name: Floors_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public."Floors_Id_seq"', 1, false);


--
-- TOC entry 3450 (class 0 OID 0)
-- Dependencies: 222
-- Name: Libraries_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public."Libraries_Id_seq"', 1, false);


--
-- TOC entry 3451 (class 0 OID 0)
-- Dependencies: 224
-- Name: Reservations_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public."Reservations_Id_seq"', 1, false);


--
-- TOC entry 3452 (class 0 OID 0)
-- Dependencies: 226
-- Name: Scanners_ScannerId_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public."Scanners_ScannerId_seq"', 1, false);


--
-- TOC entry 3453 (class 0 OID 0)
-- Dependencies: 228
-- Name: Universities_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public."Universities_Id_seq"', 1, false);


--
-- TOC entry 3454 (class 0 OID 0)
-- Dependencies: 230
-- Name: Users_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public."Users_Id_seq"', 1, false);


--
-- TOC entry 3246 (class 2606 OID 24623)
-- Name: Blocks PK_Blocks; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Blocks"
    ADD CONSTRAINT "PK_Blocks" PRIMARY KEY ("Id");


--
-- TOC entry 3252 (class 2606 OID 24625)
-- Name: Desks PK_Desks; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Desks"
    ADD CONSTRAINT "PK_Desks" PRIMARY KEY ("Id");


--
-- TOC entry 3255 (class 2606 OID 24627)
-- Name: Floors PK_Floors; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Floors"
    ADD CONSTRAINT "PK_Floors" PRIMARY KEY ("Id");


--
-- TOC entry 3258 (class 2606 OID 24629)
-- Name: Libraries PK_Libraries; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Libraries"
    ADD CONSTRAINT "PK_Libraries" PRIMARY KEY ("Id");


--
-- TOC entry 3260 (class 2606 OID 24631)
-- Name: Reservations PK_Reservations; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Reservations"
    ADD CONSTRAINT "PK_Reservations" PRIMARY KEY ("Id");


--
-- TOC entry 3262 (class 2606 OID 24633)
-- Name: Scanners PK_Scanners; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Scanners"
    ADD CONSTRAINT "PK_Scanners" PRIMARY KEY ("ScannerId");


--
-- TOC entry 3264 (class 2606 OID 24635)
-- Name: Universities PK_Universities; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Universities"
    ADD CONSTRAINT "PK_Universities" PRIMARY KEY ("Id");


--
-- TOC entry 3269 (class 2606 OID 24637)
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");


--
-- TOC entry 3271 (class 2606 OID 24639)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 3244 (class 1259 OID 24640)
-- Name: IX_Blocks_LibraryId; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_Blocks_LibraryId" ON public."Blocks" USING btree ("LibraryId");


--
-- TOC entry 3247 (class 1259 OID 24641)
-- Name: IX_Desks_BlockId; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_Desks_BlockId" ON public."Desks" USING btree ("BlockId");


--
-- TOC entry 3248 (class 1259 OID 24642)
-- Name: IX_Desks_FloorId; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_Desks_FloorId" ON public."Desks" USING btree ("FloorId");


--
-- TOC entry 3249 (class 1259 OID 24643)
-- Name: IX_Desks_ReservationId; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_Desks_ReservationId" ON public."Desks" USING btree ("ReservationId");


--
-- TOC entry 3250 (class 1259 OID 24644)
-- Name: IX_Desks_UniversityId; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_Desks_UniversityId" ON public."Desks" USING btree ("UniversityId");


--
-- TOC entry 3253 (class 1259 OID 24645)
-- Name: IX_Floors_BlockId; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_Floors_BlockId" ON public."Floors" USING btree ("BlockId");


--
-- TOC entry 3256 (class 1259 OID 24646)
-- Name: IX_Libraries_UniversityId; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_Libraries_UniversityId" ON public."Libraries" USING btree ("UniversityId");


--
-- TOC entry 3265 (class 1259 OID 24695)
-- Name: IX_Users_CardId; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_Users_CardId" ON public."Users" USING btree ("CardId");


--
-- TOC entry 3266 (class 1259 OID 24647)
-- Name: IX_Users_ReservationId; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_Users_ReservationId" ON public."Users" USING btree ("ReservationId");


--
-- TOC entry 3267 (class 1259 OID 24648)
-- Name: IX_Users_UniversityId; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_Users_UniversityId" ON public."Users" USING btree ("UniversityId");


--
-- TOC entry 3273 (class 2606 OID 24649)
-- Name: Desks FK_Desks_Blocks_BlockId; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Desks"
    ADD CONSTRAINT "FK_Desks_Blocks_BlockId" FOREIGN KEY ("BlockId") REFERENCES public."Blocks"("Id") ON DELETE CASCADE;


--
-- TOC entry 3274 (class 2606 OID 24654)
-- Name: Desks FK_Desks_Floors_FloorId; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Desks"
    ADD CONSTRAINT "FK_Desks_Floors_FloorId" FOREIGN KEY ("FloorId") REFERENCES public."Floors"("Id") ON DELETE CASCADE;


--
-- TOC entry 3275 (class 2606 OID 24659)
-- Name: Desks FK_Desks_Reservations_ReservationId; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Desks"
    ADD CONSTRAINT "FK_Desks_Reservations_ReservationId" FOREIGN KEY ("ReservationId") REFERENCES public."Reservations"("Id");


--
-- TOC entry 3276 (class 2606 OID 24664)
-- Name: Desks FK_Desks_Universities_UniversityId; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Desks"
    ADD CONSTRAINT "FK_Desks_Universities_UniversityId" FOREIGN KEY ("UniversityId") REFERENCES public."Universities"("Id") ON DELETE CASCADE;


--
-- TOC entry 3277 (class 2606 OID 24669)
-- Name: Floors lnk_Block_Floor; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Floors"
    ADD CONSTRAINT "lnk_Block_Floor" FOREIGN KEY ("BlockId") REFERENCES public."Blocks"("Id") ON DELETE CASCADE;


--
-- TOC entry 3272 (class 2606 OID 24674)
-- Name: Blocks lnk_Library_Block; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Blocks"
    ADD CONSTRAINT "lnk_Library_Block" FOREIGN KEY ("LibraryId") REFERENCES public."Libraries"("Id") ON DELETE CASCADE;


--
-- TOC entry 3279 (class 2606 OID 24679)
-- Name: Users lnk_Reservation_User; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "lnk_Reservation_User" FOREIGN KEY ("ReservationId") REFERENCES public."Reservations"("Id");


--
-- TOC entry 3278 (class 2606 OID 24684)
-- Name: Libraries lnk_University_Library; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Libraries"
    ADD CONSTRAINT "lnk_University_Library" FOREIGN KEY ("UniversityId") REFERENCES public."Universities"("Id") ON DELETE CASCADE;


--
-- TOC entry 3280 (class 2606 OID 24689)
-- Name: Users lnk_User_University; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "lnk_User_University" FOREIGN KEY ("UniversityId") REFERENCES public."Universities"("Id") ON DELETE CASCADE;


-- Completed on 2023-12-24 14:25:03

--
-- PostgreSQL database dump complete
--

